### ISSUE TITLE
Upgrade SupportLib dependency to AndroidX

### ISSUE THREAD

**Issue by sridhar-vadlamani-ck** [SchibstedSpain/Barista#262]
AndroidX is the latest and greatest by Google. As 28 is the last support lib version, upgrading to androidx will futureproof this.

**Comment by Sloy** [comment]
The problem with using AndroidX is that we will force library users to update to AndroidX too. Is that right? That's not something we want to do at the moment, not until AndroidX is more widespread.

We haven't migrated to AndroidX internally yet, but if I'm not mistaken the Jetifier tool allows apps to use libraries consuming the support library. So this should not be a blocking issue.

Let me know if I got something wrong.

**Comment by Sloy** [comment]
But let's keep the issue open, because we'll want to do it someday 😄

**Comment by lachudra87** [comment]
Problem with Jetifier and AndroidX in case of barista lib is that `uiautomator-v18` is only in alpha version for AndroidX and it looks like only non v18 version of `uiautomator` is supported. So Jetifier won't override `uiautomator-v18` and there will be duplicated class definition in dex. Solution is to manually exclude `ui-automator-v18` from barista import with sth like below:
```
    androidTestImplementation ('com.schibsted.spain:barista:2.7.0') {
        exclude group: 'com.android.support.test.uiautomator', module: 'uiautomator-v18'
    }
```
But maybe it is possible to change of `uiautomator` implementation in barista itself to make life of developers a little bit easier ;)

**Comment by DeanPike** [comment]
Would it be possible to create a branch of the library that uses androidx so that we can use the latest version of espresso as it looks like the pre androidx versions of espresso are not going to be supported any more.

As of version 3.1.0 Espresso seems to have migrated to androidx libraries.
com.android.support.test.espresso.espresso-core version 3.0.2 was last updated in Apr 2018
androidx.test.espresso.espresso-core version 3.1.1 was last updated in Dec 2018

**Comment by Sloy** [comment]
@DeanPike maybe we should just release a 3.0.0 version of Barista including AndroidX. Everyone using the support lib can still use Barista 2.x until they migrate. They would not get new features though.

What do you think @alorma @rocboronat @sergiocastilloscmspain ?

**Comment by Sloy** [comment]
@lachudra87 hmm let me check that, because I recently migrated a project to AndroidX using Barista and didn't have any problems with uiautomator. 
In any case, we'll try to do as much as possible to make Barista compatible with Jetifier.

**Comment by mrk-han** [comment]
Right now, is Barista compatible with AndroidX.Test?

**Comment by Sloy** [comment]
@mrk-han If you include UIAutomator in your dependencies you must apply the workaround by @lachudra87 [here](https://github.com/SchibstedSpain/Barista/issues/262#issuecomment-448905447). 
Otherwise, it should be fine. We're using Barista in a big production project with AndroidX and it's running fine. If you find any specific issue please let us know.

**Comment by serandel** [comment]
I've got other classes being mangled by Jetifier, as in #281 :(

**Comment by rocboronat** [comment]
Sorry @Sloy, just read the question! It's great for me to move on with 3.0.0 with androidx support. But honestly, as I'm a bit disconnected of the reality, I don't know how widespread androidx is...

**Comment by serandel** [comment]
I have a branch with the library already migrated to AndroidX, but I'm hitting problems in 5 tests from the sample app: 4 of them are about Mockito and ByteBuddy and 1 because of Glide. All related to Jetifier.

I had no time to sort them out, but if it's useful in its current state, so you don't have to start from zero, feel free to use it: https://github.com/serandel/barista

**Comment by kenyee** [comment]
Jetifier doesn't seem to work on everything...e.g., I hit this:

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/test/espresso/core/internal/deps/guava/base/Preconditions;
at com.schibsted.spain.barista.internal.viewaction.AutoCompleteViewActions$ReplaceAutoCompleteTextAction.<init>(AutoCompleteViewActions.java:39)
at com.schibsted.spain.barista.internal.viewaction.AutoCompleteViewActions.replaceAutoComplete(AutoCompleteViewActions.java:24)
at com.schibsted.spain.barista.interaction.BaristaAutoCompleteTextViewInteractions.writeToAutoComplete(BaristaAutoCompleteTextViewInteractions.kt:22)
...
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
```

Using latest version of Barista w/ these excludes:
```
    androidTestImplementation("com.schibsted.spain:barista:${baristaVersion}") {
        exclude group: 'com.android.support'
        exclude group: 'org.jetbrains.kotlin'
        exclude group: 'com.android.support.test.uiautomator', module: 'uiautomator-v18'
    }
```
